/*
SQLyog Community v13.1.6 (64 bit)
MySQL - 8.0.22 : Database - proyecthiber
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`proyecthiber` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;

USE `proyecthiber`;

/*Table structure for table `PIEZAS` */

DROP TABLE IF EXISTS `PIEZAS`;

CREATE TABLE `PIEZAS` (
  `CODIGO` varchar(6) COLLATE utf8_spanish_ci NOT NULL,
  `NOMBRE` varchar(20) COLLATE utf8_spanish_ci NOT NULL,
  `PRECIO` float NOT NULL,
  `DESCRIPCION` text COLLATE utf8_spanish_ci,
  PRIMARY KEY (`CODIGO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;

/*Table structure for table `PROVEEDORES` */

DROP TABLE IF EXISTS `PROVEEDORES`;

CREATE TABLE `PROVEEDORES` (
  `CODIGO` varchar(6) COLLATE utf8_spanish_ci NOT NULL,
  `NOMBRE` varchar(20) COLLATE utf8_spanish_ci NOT NULL,
  `APELLIDOS` varchar(30) COLLATE utf8_spanish_ci NOT NULL,
  `DIRECCION` varchar(40) COLLATE utf8_spanish_ci NOT NULL,
  `ESTADO` varchar(4) COLLATE utf8_spanish_ci DEFAULT NULL,
  PRIMARY KEY (`CODIGO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;

/*Table structure for table `PROYECTOS` */

DROP TABLE IF EXISTS `PROYECTOS`;

CREATE TABLE `PROYECTOS` (
  `CODIGO` varchar(6) COLLATE utf8_spanish_ci NOT NULL,
  `NOMBRE` varchar(40) COLLATE utf8_spanish_ci NOT NULL,
  `CIUDAD` varchar(40) COLLATE utf8_spanish_ci DEFAULT NULL,
  PRIMARY KEY (`CODIGO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;

/*Table structure for table `GESTIONES` */

DROP TABLE IF EXISTS `GESTIONES`;

CREATE TABLE `GESTIONES` (
  `CODIGO` int NOT NULL AUTO_INCREMENT,
  `CODPROVEEDOR` varchar(6) COLLATE utf8_spanish_ci NOT NULL,
  `CODPROYECTO` varchar(6) COLLATE utf8_spanish_ci NOT NULL,
  PRIMARY KEY (`CODIGO`),
  KEY `CODPROVEEDOR` (`CODPROVEEDOR`),
  KEY `CODPROYECTO` (`CODPROYECTO`),
  CONSTRAINT `GESTIONES_ibfk_1` FOREIGN KEY (`CODPROVEEDOR`) REFERENCES `PROVEEDORES` (`CODIGO`),
  CONSTRAINT `GESTIONES_ibfk_2` FOREIGN KEY (`CODPROYECTO`) REFERENCES `PROYECTOS` (`CODIGO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;

/*Table structure for table `GESTIONESPIEZAS` */

DROP TABLE IF EXISTS `GESTIONESPIEZAS`;

CREATE TABLE `GESTIONESPIEZAS` (
  `CODIGO` int NOT NULL AUTO_INCREMENT,
  `CODPIEZA` varchar(6) COLLATE utf8_spanish_ci NOT NULL,
  `CODGESTION` int NOT NULL,
  PRIMARY KEY (`CODIGO`),
  KEY `CODPIEZA` (`CODPIEZA`),
  KEY `CODGESTION` (`CODGESTION`),
  CONSTRAINT `GESTIONESPIEZAS_ibfk_1` FOREIGN KEY (`CODPIEZA`) REFERENCES `PIEZAS` (`CODIGO`),
  CONSTRAINT `GESTIONESPIEZAS_ibfk_2` FOREIGN KEY (`CODGESTION`) REFERENCES `GESTIONES` (`CODIGO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
